# 1. 1D Matrices with Spin Changes Prohibited (Hopping Motion and Spin are Decoupled)

In [17]:
# The system analyzed will be a 1D cycle matrix with spin, but the change in spin direction is not allowed when hopping. 

# Importing required libraries
import numpy as np

# Defining required constants
J = 1
valid_input = False

# 1. Generating a 1D Cycle Adjacency Matrix with Spin (Each Node has 2 Spin States) 

# Defining a function that generates a 1D adjacency matrix of varying amounts of nodes (each with 2 spin states) with periodic 
# boundary conditions depending on user input.
def create_cycle_adjacency_matrix_with_spin(num_nodes):
    # For each number of nodes, there must be 2x that in the adjacency matrix to account for the fact that each node has 2 spin states.
    num_nodes = num_nodes * 2
    
    # Creating a square matrix with the row and column number desired by the user. 
    #The matrix will initially only contain zeros as entries.
    adjacency_matrix = np.zeros((num_nodes, num_nodes)) 
    
    # Changing the required matrix elements from 0 to 1 to indicate a possible hopping site using periodic boundary conditions.
    for i in range (num_nodes):
     # generated_matrix[row][column]
    # Now the cycle conditions are applied so that each node is connected to its nearest spin matching neighbor which is 2 nodes away. 
        adjacency_matrix[i][(i + 2) %num_nodes] = 1 
        adjacency_matrix[i][(i - 2) %num_nodes] = 1
        
    return(adjacency_matrix)

# Calling for user input to generate desired matrix
while valid_input == False:

    try:
        num_nodes = int(input("Enter desired number of nodes for the 1D cycle adjacency matrix: "))
    
        if num_nodes < 2:
            print("The number of nodes must be at least 2 and an integer. Re-input the number of nodes desired.")
        else:
            # Generating and printing the desired matrix
            adjacency_matrix =  create_cycle_adjacency_matrix_with_spin(num_nodes)
            print("Cycle Adjacency Matrix when Spin Changes Prohibited:")
            print(adjacency_matrix)
            valid_input = True
    
    except ValueError:
        print("The number of nodes must be an integer. Re-input the number of nodes desired.")

def create_hamiltonian_1D(adjacency_matrix):
# H = -JA, where the parameter J will be set as 1 for now. 
    hamiltonian_1D = (-1) * J * adjacency_matrix
    
    return(hamiltonian_1D)

hamiltonian_1D = create_hamiltonian_1D(adjacency_matrix)
print("Hamiltonian Matrix:")
print(hamiltonian_1D)

# 3. Determining the Eigenvectors and Eigenvalues 
ham_1D_eigenvalues, ham_1D_eigenvectors = np.linalg.eig(hamiltonian_1D)
print(f"Eigenvalues of the hamiltonian of a system of {num_nodes} nodes:", ham_1D_eigenvalues)
# The eigenvectors are displayed as column vectors
print(f"Eigenvectors of the hamiltonian of a system of {num_nodes} nodes: \n", ham_1D_eigenvectors)

Enter desired number of nodes for the 1D cycle adjacency matrix:  3


Cycle Adjacency Matrix when Spin Changes Prohibited:
[[0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]]
Hamiltonian Matrix:
[[-0. -0. -1. -0. -1. -0.]
 [-0. -0. -0. -1. -0. -1.]
 [-1. -0. -0. -0. -1. -0.]
 [-0. -1. -0. -0. -0. -1.]
 [-1. -0. -1. -0. -0. -0.]
 [-0. -1. -0. -1. -0. -0.]]
Eigenvalues of the hamiltonian of a system of 3 nodes: [ 1. -2.  1. -2.  1.  1.]
Eigenvectors of the hamiltonian of a system of 3 nodes: 
 [[-8.16496581e-01  5.77350269e-01 -1.35118573e-01  5.42329534e-02
   1.05586286e-02  2.80303678e-02]
 [-4.27325041e-17  1.20471054e-16 -8.05238870e-01 -5.74797460e-01
   8.80937767e-02  1.67046921e-01]
 [ 4.08248290e-01  5.77350269e-01  6.75592866e-02  5.42329534e-02
   4.30989513e-01  2.79098320e-01]
 [ 0.00000000e+00 -5.35130709e-17  4.02619435e-01 -5.74797460e-01
   5.07102376e-01 -7.10074889e-01]
 [ 4.08248290e-01  5.77350269e-01  6.75592866e-02  5.42329534e-02
  -4.41548141e-01 -3.0712868

# 2D Matrices with Spin Changes Prohibited (Hopping Motion and Spin are Decoupled)

In [15]:
# Creating the 2D Hamiltonian where changes in spin are prohibited when hopping. First, the 2D Hamiltonian will be created for only 
# upspin hopping and downspin hopping respectively using the tensor products of the 1D Hamiltonians for upspin/downspin hopping in the x and 
# y directions. Then these two 2D Hamiltonians will be combined to create an effective 2D Hamiltonian that describes the whole system.

# Model for the Hamiltonian of a 2D lattice: H_x (tensor product) I_y + I_x (tensor product) H_y

# Importing required libraries
import numpy as np

# Defining required constants.
valid_input = False
J = 1

# Defining requirments for user input.
while valid_input == False:
    try:
        x_nodes = int(input("Enter the desired number of nodes in the x-direction: "))
        y_nodes = int(input("Enter the desired number of nodes in the y-direction: "))
        
        if x_nodes < 2 or y_nodes < 2:
            print("Each dimension must have at least 2 nodes.")
        elif x_nodes != y_nodes:
            print(" The x and y dimensions must be equal to form a square lattice.")
        else:
            valid_input = True
    except ValueError:
        print("The number of nodes must be an integer. Re-input the number of nodes desired.")


# Creating the 1D Hamiltonian for hopping amongst only the up-spin states.
# This is the same as creating the 1D Hamiltonian for a system with no spin (nearest neighbor hopping model). 

# Defining the number of nodes for the 1D system to be the number of x nodes (or equivalently y nodes).
num_nodes = x_nodes

# Defining a function to create the adjacency matrix for a 1D system.
def create_1D_cycle_adjacency_matrix(num_nodes):
    
    # Creating a square matrix with the row and column number desired by the user. 
    #The matrix will initially only contain zeros as entries.
    adjacency_matrix = np.zeros((num_nodes, num_nodes)) 
    
    # Changing the required matrix elements from 0 to 1 to indicate a possible hopping site using periodic boundary conditions.
    for i in range (num_nodes):
     # generated_matrix[row][column]
    # Now the cycle conditions are applied so that each node is connected to its nearest spin matching neighbor.        
        adjacency_matrix[i][(i + 1) %num_nodes] = 1 
        adjacency_matrix[i][(i - 1) %num_nodes] = 1
        
    return(adjacency_matrix)

# Defining a function to create the hamiltonian matrix for a 1D system.
def create_1D_hamiltonian(adjacency_matrix):
    
    # H = -JA, where the parameter J will be set as 1 for now. 
    hamiltonian_1D = (-1) * J * adjacency_matrix
    
    return(hamiltonian_1D)

# Defining a function to create the hamiltonian for a 2D system from the soleyly up-spin or down-spin hopping 1D systems. 
def create_2D_hamiltonian(x_nodes, y_nodes, hamiltonian_1D_matrix):
    # Creating the x and y identity matrices.
    identity_x = np.eye(x_nodes) # Creates a (x_nodes) x (x_nodes) identity matrix.
    identity_y = np.eye(y_nodes) # Creates a (y_nodes) x (y_nodes) identity matrix.
    
    # Defining the 1D Hamiltonian for hopping in the x and y directions respectively.
    hamiltonian_x = hamiltonian_1D_matrix
    hamiltonian_y = hamiltonian_1D_matrix
    
    # Creating the 2D Hamiltonian from the model H_2D = H_x (tensor product) I_y + I_x (tensor product) H_y
    hamiltonian_2D = np.kron(hamiltonian_x, identity_y) + np.kron(identity_x, hamiltonian_y)
    return (hamiltonian_2D)

# Defining a function to create the effective hamiltonian which includes both spin state hoppings (but no interchange of spin state).
def create_total_hamiltonian(h_up, h_down):
    h_zeros = np.zeros_like(h_up)
    h_total = np.block([[h_up, h_zeros], 
                       [h_zeros, h_down]])
    
    return (h_total)

# Creating both the 1D adjacency and 1D hamiltonian matrices for up-spin and down-spin hopping respectivelly.
upspin_1D_adjacency_matrix = create_1D_cycle_adjacency_matrix(num_nodes)
upspin_1D_hamiltonian = create_1D_hamiltonian(upspin_1D_adjacency_matrix)

downspin_1D_adjacency_matrix = create_1D_cycle_adjacency_matrix(num_nodes)
downspin_1D_hamiltonian = create_1D_hamiltonian(downspin_1D_adjacency_matrix)
 
# Creating the 2D hamiltonian matrices for up-spin and down-spin hopping respectivelly.
upspin_2D_hamiltonian = create_2D_hamiltonian(x_nodes, y_nodes, upspin_1D_hamiltonian)
downspin_2D_hamiltonian = create_2D_hamiltonian(x_nodes, y_nodes, downspin_1D_hamiltonian)

# Creating the combined effective hamiltonian which includes both spin state hoppings (but no interchange of spin state).
spin_no_interchange_2D_hamiltonian = create_total_hamiltonian(upspin_2D_hamiltonian, downspin_2D_hamiltonian)

print(f"The Hamiltonian of a 2D {x_nodes} x {y_nodes} lattice with spin states (no interchange in these states):")
print(spin_no_interchange_2D_hamiltonian)


# Determining the eigenvalues and eigenvectors from the Hamiltonian of the 2D square lattice.
spin_no_interchange_2D_ham_eigenvalues, spin_no_interchange_2D_ham__eigenvectors = np.linalg.eigh(spin_no_interchange_2D_hamiltonian)
print(f"Eigenvalues of the Hamiltonian of a 2D {x_nodes} x {y_nodes} lattice: \n{np.round(spin_no_interchange_2D_ham_eigenvalues, 1)}")
# The eigenvectors are displayed as column vectors.
print(f"Eigenvectors of the Hamiltonian of a 2D {x_nodes} x {y_nodes} lattice: \n", spin_no_interchange_2D_ham__eigenvectors)

Enter the desired number of nodes in the x-direction:  3
Enter the desired number of nodes in the y-direction:  3


The Hamiltonian of a 2D 3 x 3 lattice with spin states (no interchange in these states):
[[-0. -1. -1. -1. -0. -0. -1. -0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -0. -1. -0. -1. -0. -0. -1. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -0. -0. -0. -1. -0. -0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -0. -0. -0. -1. -1. -1. -0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -1. -0. -1. -0. -1. -0. -1. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0. -1. -1. -1. -0. -0. -0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -0. -0. -1. -0. -0. -0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -1. -0. -0. -1. -0. -1. -0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0. -1. -0. -0. -1. -1. -1. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -0. -1. -1. -1. -0. -0. -1. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -0. -1. -0. -1. -0. -0. -1. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1. -0. -0. -0. -1. -0. -0. -1.]
 [ 0.  0.  