# Hopping on a 1D Lattice where the Change of Spin Direction Allowed

In [27]:
# The system analyzed will be a 1D cyle matrix with spin, where a change in spin is allowed when hopping. 

# Importing required libraries.
import numpy as np

# Defining required constants.
J = 1
valid_input = False

# Generating a 1D cycle Adjacency Matrix with Spin (Each Node has 2 Spin States) in which spin direction changes are allowed when hopping.

# Defining a function that generates a 1D adjacency matrix of varying amounts of nodes (each with 2 spin states) with periodic 
# boundary conditions depending on user input.
def create_cycle_adjacency_matrix_with_spin(num_nodes):
    # For each number of nodes, there must be 2x that in the adjacency matrix to account for the fact that each node has 2 spin states.
    num_nodes = num_nodes * 2
    
    # Creating a square matrix with the row and column number desired by the user. 
    #The matrix will initially only contain zeros as entries.
    adjacency_matrix = np.zeros((num_nodes, num_nodes)) 
    
    # Changing the required matrix elements from 0 to 1 to indicate a possible hopping site using periodic boundary conditions.

    # Creating a loop that will account for connections of a spin-up state to the nearest spin-up states and/or of a spin-down state 
    # to the nearest spin-down states (aka the hops possible when there is no spin direction switching at each node). 
    for i in range (num_nodes):
     # generated_matrix[row][column]

        adjacency_matrix[i][(i + 2) %num_nodes] = 1 
        adjacency_matrix[i][(i - 2) %num_nodes] = 1

    # Saving a copy of the spin-conserving matrix.
    spin_conserving_adjacency_matrix = np.copy(adjacency_matrix)

    # Creating a loop that will account for hops possible specifically when spin direction can switch.
    for i in range (num_nodes):
        
        if (i % 2 != 0): # Checking to see if row index i is odd.
            # Adding the only upspin hopping possibilities to the only downspin hopping possibilities to get 
            # the hopping possibilites when spin interchange is allowed for each node.
            adjacency_matrix[i] += spin_conserving_adjacency_matrix[i - 1]
            
        elif (i % 2 == 0): # Checking to see if row index i is even.
            # Adding the only upspin hopping possibilities to the only downspin hopping possibilities to get 
            # the hopping possibilites when spin interchange is allowed for each node.
            adjacency_matrix[i] += spin_conserving_adjacency_matrix[i + 1]

    return(adjacency_matrix)


# Calling for user input to generate desired matrix.
while valid_input == False:

    try:
        num_nodes = int(input("Enter desired number of nodes for the 1D cycle adjacency matrix: "))
    
        if num_nodes < 2:
            print("The number of nodes must be at least 2 and an integer. Re-input the number of nodes desired.")
        else:
            # Generating and printing the desired matrix.
            adjacency_matrix =  create_cycle_adjacency_matrix_with_spin(num_nodes)
            print("1D Cycle Adjacency Matrix when Spin Changes are Allowed:")
            print(adjacency_matrix)
            valid_input = True
    
    except ValueError:
        print("The number of nodes must be an integer. Re-input the number of nodes desired.")

# Creating the Hamiltonian Matrix.
def create_hamiltonian_1D(adjacency_matrix):
# H = -JA, where the parameter J will be set as 1 for now. 
    hamiltonian_1D = (-1) * J * adjacency_matrix
    
    return(hamiltonian_1D)

hamiltonian_1D_spin_interchange_allowed = create_hamiltonian_1D(adjacency_matrix)
print("Hamiltonian Matrix:")
print(hamiltonian_1D_spin_interchange_allowed)

# 4. Determining the Eigenvectors and Eigenvalues.
ham_1D_spin_interchange_allowed_eigenvalues, ham_1D_spin_interchange_allowed_eigenvectors = np.linalg.eig(hamiltonian_1D_spin_interchange_allowed)
print(f"Eigenvalues of the hamiltonian of a system of {num_nodes} nodes:", np.round(ham_1D_spin_interchange_allowed_eigenvalues, 0))
# The eigenvectors are displayed as column vectors.
print(f"Eigenvectors of the hamiltonian of a system of {num_nodes} nodes: \n", ham_1D_spin_interchange_allowed_eigenvectors)

Enter desired number of nodes for the 1D cycle adjacency matrix:  3


1D Cycle Adjacency Matrix when Spin Changes are Allowed:
[[0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
Hamiltonian Matrix:
[[-0. -0. -1. -1. -1. -1.]
 [-0. -0. -1. -1. -1. -1.]
 [-1. -1. -0. -0. -1. -1.]
 [-1. -1. -0. -0. -1. -1.]
 [-1. -1. -1. -1. -0. -0.]
 [-1. -1. -1. -1. -0. -0.]]
Eigenvalues of the hamiltonian of a system of 3 nodes: [-4.  0.  2.  2.  0. -0.]
Eigenvectors of the hamiltonian of a system of 3 nodes: 
 [[ 4.08248290e-01 -7.07106781e-01 -5.77350269e-01  1.47694255e-01
  -2.51904285e-16 -1.05545255e-16]
 [ 4.08248290e-01  7.07106781e-01 -5.77350269e-01  1.47694255e-01
   2.19285227e-16  1.61056406e-16]
 [ 4.08248290e-01  1.62732113e-17  2.88675135e-01  4.09515889e-01
  -5.52202296e-01  1.75470265e-16]
 [ 4.08248290e-01  1.62732113e-17  2.88675135e-01  4.09515889e-01
   5.52202296e-01 -2.27462030e-16]
 [ 4.08248290e-01  1.62732113e-17  2.88675135e-01 -5.57210144e-01
  -4.41670267e-01 -7.071

# Hopping on a 2D Lattice where the Change of Spin Direction Allowed.

In [13]:
# The system analyzed will be a 1D cyle matrix with spin, where a change in spin is allowed when hopping. 

# The effective Hamiltonian that will describe the entire 2D system will be constructed in the following block diagonal style:

# H_tot = ( H_up_to_up     H_up_to_down   )
#         ( H_down_to_up   H_down_to_down )

# First, the 2D Hamiltonian will be created for hopping along upspin states only and hopping along downspin states only respectively 
# using the tensor products of the 1D Hamiltonians for upspin/downspin hopping in the x and y directions. 

# The 2D Hamiltonian for hopping from an upspin state to a neighboring downspin state and the 2D Hamiltonian for hopping from 
# a downspin state to a neighboring upspin state will then be created respectively.

# Model for the Hamiltonian of a 2D lattice: H_x (tensor product) I_y + I_x (tensor product) H_y

# Importing required libraries.
import numpy as np

# Defining required constants.
valid_input = False
J = 1

# Calling for user input.
while valid_input == False:
    try:
        x_nodes = int(input("Enter the desired number of nodes in the x-direction: "))
        y_nodes = int(input("Enter the desired number of nodes in the y-direction: "))
        
        if x_nodes < 2 or y_nodes < 2:
            print("Each dimension must have at least 2 nodes.")
        elif x_nodes != y_nodes:
            print(" The x and y dimensions must be equal to form a square lattice.")
        else:
            valid_input = True
    except ValueError:
        print("The number of nodes must be an integer. Re-input the number of nodes desired.")

# Creating the 1D Hamiltonian for:

# - Hopping from an up-spin state to any other neighboring up-spin state only.
# - Hopping from a down-spin state to any other neighboring down-spin state only.
# - Hopping from an up-spin state to any other neighboring down-spin state only.
# - Hopping from a down-spin state to any other neighboring up-spin state only.

# Creating all these Hamiltonians is the same as creating the 1D Hamiltonian for a system with no spin (nearest neighbor hopping model). 

# Defining the number of nodes for the 1D system to be the number of x nodes (or equivalently y nodes).
num_nodes = x_nodes

# Defining a function to create the adjacency matrix for a 1D system (nearest neighbor hopping model).
def create_1D_cycle_adjacency_matrix(num_nodes):
    
    # Creating a square matrix with the row and column number desired by the user. 
    #The matrix will initially only contain zeros as entries.
    adjacency_matrix = np.zeros((num_nodes, num_nodes)) 
    
    # Changing the required matrix elements from 0 to 1 to indicate a possible hopping site using periodic boundary conditions.
    for i in range (num_nodes):
     # generated_matrix[row][column]
    # Now the cycle conditions are applied so that each node is connected to its nearest spin matching neighbor.        
        adjacency_matrix[i][(i + 1) %num_nodes] = 1 
        adjacency_matrix[i][(i - 1) %num_nodes] = 1
        
    return(adjacency_matrix)

# Defining a function to create the hamiltonian matrix for a 1D system (nearest neighbor hopping model).
def create_1D_hamiltonian(adjacency_matrix):
    
    # H = -JA, where the parameter J will be set as 1 for now. 
    hamiltonian_1D = (-1) * J * adjacency_matrix
    
    return(hamiltonian_1D)

# Defining a function to create the hamiltonian for a 2D system from the up-spin to up-spin, down-spin to down-spin, up-spin to down-spin,
# and down-spin to up-spin hopping 1D systems. 
def create_2D_hamiltonian(x_nodes, y_nodes, hamiltonian_1D_matrix):
    # Creating the x and y identity matrices.
    identity_x = np.eye(x_nodes) # Creates a (x_nodes) x (x_nodes) identity matrix.
    identity_y = np.eye(y_nodes) # Creates a (y_nodes) x (y_nodes) identity matrix.
    
    # Defining the 1D Hamiltonian for hopping in the x and y directions respectively.
    hamiltonian_x = hamiltonian_1D_matrix
    hamiltonian_y = hamiltonian_1D_matrix
    
    # Creating the 2D Hamiltonian from the model H_2D = H_x (tensor product) I_y + I_x (tensor product) H_y
    hamiltonian_2D = np.kron(hamiltonian_x, identity_y) + np.kron(identity_x, hamiltonian_y)
    return (hamiltonian_2D)

# Defining a function to create the effective hamiltonian which includes all hopping possibilities (interchange of spin state is now allowed).
def create_total_hamiltonian(h_up_to_up, h_down_to_down, h_up_to_down, h_down_to_up):
    h_total = np.block([[h_up_to_up, h_up_to_down], 
                       [h_down_to_up, h_down_to_down]])
    
    return (h_total)

# Creating both the 1D adjacency and 1D hamiltonian matrices for up-spin to up-spin, down-spin to down-spin, up-spin to down-spin,
# and down-spin to up-spin hopping respectivelly.
up_to_up_1D_adjacency_matrix = create_1D_cycle_adjacency_matrix(num_nodes)
up_to_up_1D_hamiltonian = create_1D_hamiltonian(up_to_up_1D_adjacency_matrix)

down_to_down_1D_adjacency_matrix = create_1D_cycle_adjacency_matrix(num_nodes)
down_to_down_1D_hamiltonian = create_1D_hamiltonian(down_to_down_1D_adjacency_matrix)

up_to_down_1D_adjacency_matrix = create_1D_cycle_adjacency_matrix(num_nodes)
up_to_down_1D_hamiltonian = create_1D_hamiltonian(up_to_down_1D_adjacency_matrix)

down_to_up_1D_adjacency_matrix = create_1D_cycle_adjacency_matrix(num_nodes)
down_to_up_1D_hamiltonian = create_1D_hamiltonian(down_to_up_1D_adjacency_matrix)
 
# Creating the 2D hamiltonian matrices for up-spin to up-spin, down-spin to down-spin, up-spin to down-spin,
# and down-spin to up-spin hopping respectivelly.
up_to_up_2D_hamiltonian = create_2D_hamiltonian(x_nodes, y_nodes, up_to_up_1D_hamiltonian)
down_to_down_2D_hamiltonian = create_2D_hamiltonian(x_nodes, y_nodes, down_to_down_1D_hamiltonian)
up_to_down_2D_hamiltonian = create_2D_hamiltonian(x_nodes, y_nodes, up_to_down_1D_hamiltonian)
down_to_up_2D_hamiltonian = create_2D_hamiltonian(x_nodes, y_nodes, down_to_up_1D_hamiltonian)

# Creating the combined effective hamiltonian which includes all possible hoppings (interchange of spin state is now allowed).
spin_interchange_2D_hamiltonian = create_total_hamiltonian(up_to_up_2D_hamiltonian, down_to_down_2D_hamiltonian, up_to_down_2D_hamiltonian, down_to_up_2D_hamiltonian)

print(f"The Hamiltonian of a 2D {x_nodes} x {y_nodes} lattice with spin states (where the interchange of these states when hopping is allowed):")
print(spin_interchange_2D_hamiltonian)


# Determining the eigenvalues and eigenvectors from the Hamiltonian of the 2D square lattice.
spin_interchange_2D_ham_eigenvalues, spin_interchange_2D_ham_eigenvectors = np.linalg.eigh(spin_interchange_2D_hamiltonian)
print(f"Eigenvalues of the Hamiltonian of a 2D {x_nodes} x {y_nodes} lattice: \n{np.round(spin_interchange_2D_ham_eigenvalues, 1)}")
# The eigenvectors are displayed as column vectors.
print(f"Eigenvectors of the Hamiltonian of a 2D {x_nodes} x {y_nodes} lattice: \n", spin_interchange_2D_ham_eigenvectors)

Enter the desired number of nodes in the x-direction:  3
Enter the desired number of nodes in the y-direction:  3


The Hamiltonian of a 2D 3 x 3 lattice with spin states (where the interchange of these states when hopping is allowed):
[[-0. -1. -1. -1. -0. -0. -1. -0. -0. -0. -1. -1. -1. -0. -0. -1. -0. -0.]
 [-1. -0. -1. -0. -1. -0. -0. -1. -0. -1. -0. -1. -0. -1. -0. -0. -1. -0.]
 [-1. -1. -0. -0. -0. -1. -0. -0. -1. -1. -1. -0. -0. -0. -1. -0. -0. -1.]
 [-1. -0. -0. -0. -1. -1. -1. -0. -0. -1. -0. -0. -0. -1. -1. -1. -0. -0.]
 [-0. -1. -0. -1. -0. -1. -0. -1. -0. -0. -1. -0. -1. -0. -1. -0. -1. -0.]
 [-0. -0. -1. -1. -1. -0. -0. -0. -1. -0. -0. -1. -1. -1. -0. -0. -0. -1.]
 [-1. -0. -0. -1. -0. -0. -0. -1. -1. -1. -0. -0. -1. -0. -0. -0. -1. -1.]
 [-0. -1. -0. -0. -1. -0. -1. -0. -1. -0. -1. -0. -0. -1. -0. -1. -0. -1.]
 [-0. -0. -1. -0. -0. -1. -1. -1. -0. -0. -0. -1. -0. -0. -1. -1. -1. -0.]
 [-0. -1. -1. -1. -0. -0. -1. -0. -0. -0. -1. -1. -1. -0. -0. -1. -0. -0.]
 [-1. -0. -1. -0. -1. -0. -0. -1. -0. -1. -0. -1. -0. -1. -0. -0. -1. -0.]
 [-1. -1. -0. -0. -0. -1. -0. -0. -1. -1. -1. -0. -0. -